"""empty message

Revision ID: 844580306178
Revises: 0668885910d5
Create Date: 2020-05-28 15:25:58.436246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844580306178'
down_revision = '0668885910d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
